@echo off
echo Starting development server...
echo Adding Node.js to PATH...
SET PATH=%PATH%;C:\Program Files\nodejs
SET DEBUG=express:*
echo Running tsx with debug info...
node_modules\.bin\tsx server/index.ts 